FROM ubuntu:18.04

RUN apt update && \
    apt install python3-distutils -y && \
    apt install curl -y

RUN curl https://bootstrap.pypa.io/pip/3.6/get-pip.py -o get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py && \
    pip install notebook

RUN jupyter notebook --generate-config -y && \
    echo "c = get_config()" >> /root/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.ip = '0.0.0.0'" >> /root/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.open_browser = False" >> /root/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.password_required = False" >> /root/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.port = 8888" >> /root/.jupyter/jupyter_notebook_config.py && \
    mkdir -p /root/notebook


EXPOSE 8888:8888

CMD ["jupyter","notebook","--allow-root"]